### ISSUE TITLE
Buggy scrollbar

### ISSUE THREAD

**Issue by jenstornell** [Remix-Design/remixicon#1]
The scrollbar on the site has a lot of bugs. It's because it does not use the native scrollbar, but a library. I think function is more important than look in this case.

Personally in my projects I use only css to enhance the look of the scrollbar. I suggest you do the same. When all browsers support it, you just need to make minor css changes.

https://css-tricks.com/the-current-state-of-styling-scrollbars/

**Comment by xiaochunjimmy** [comment]
Thank you very much for raising a bug and even with a solution to help us improve our products. 
We hope we'll fix it in the next version of our website. 
If you can tell us more details about the bug, we would be very grateful.

**Comment by jenstornell** [comment]
@xiaochunjimmy I use Windows 10 with Google Chrome.

About the bugs. It's very many nags here and there. Some of them only accur sometimes.

- Shortcut keys that stop working like "home", "page down" and "end" for example.
- The size of the scroll handle is miscalculated.
- The scroll handle position is wrong sometimes.
- The scroll handle is jumping around on drag sometimes.
- If I click below the scrollbar it should jump down. Instead it jumps up.
- The scrollbar does not scroll all the way down.

There are so many small things with a library like this that I hope that you go back to the native scrollbar that is always reliable.

**Comment by xiaochunjimmy** [comment]
Hi, jenstornell~
We've fixed the bugs of scrollbar, please have a look whether it's OK now~
We removed the library and used pure CSS to customize the style of the scrollbar.

**Comment by jenstornell** [comment]
@xiaochunjimmy Hmm, I don't see a scrollbar at all in Google Chrome on a computer. I refreshed the CSS but still no luck. On a mobile device however it works as expected.

**Comment by jenstornell** [comment]
Not sure if you changed anything but now it's working for me here on a computer as well.

**Comment by xiaochunjimmy** [comment]
Hmmmmm... Our scroll bar does not seem to be obvious enough.
hank you for your advice~ We'll make it looked better in the next version.

**Comment by xiaochunjimmy** [comment]
Hi, man~
Is there still any problems with the scrollbar? If everything's OK, I'll close this issue~

**Comment by jenstornell** [comment]
Seems to work great now! :)
